events {}

http {

    upstream location_service {
        server location-service:8000;
    }

    upstream map_service {
        server map-service:8000;
    }

    upstream poster_service {
        server poster-service:8000;
    }

    server {

        listen 80;

        location /api/locations/ {
            proxy_pass http://location_service/;
        }

        location /api/maps/ {
            proxy_pass http://map_service/;
        }

        location /api/posters/ {
            proxy_pass http://poster_service/;
        }

    }
}